### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by halcyonera** [jffrymrtn/writeily-pro#119] opened 2015-04-26 06:14 UTC
Thanks for this great FOSS app!

~~Just a feature request, I wish there is an option to toggle line break.~~

~~I'm not sure if automatic line break function is intentionally omitted or not, but this option will increase its readability. Sometimes it's really tricky to edit long text.~~

Sorry, it seems there is a bug that syntax highlighting option is disabling line break and makes a ridiculous horizontal scroll bar...

**Comment by plafue** [comment] 2015-04-26 07:20
Duplicate of #113. I just closed it! Thank you for your feedback :+1:

**Closed by plafue** 2015-04-26 07:20 UTC
Labels: duplicate
